List<String> nameList = [
  'Aaya fir vo najar ese',
  "Main Dhoondne Ko Zamaane Mein",
  'Dil ke Pass ',
  'Jo  tu mera hamdarad hai',
  'Teri Galliya',
  'Hasi ban gae',
  'Aam jehe munde',
  'One Love',
  'Tukur Tukur',
  'Man ma Emotion',
  'Keh du tumhe',
  'Dill meri Na sune',
  'Tera Fitoor',
  'Rabba Rabba',
  'Arjan vally',
  'Saari Duniya jala dege',
  'Jabal jabal',
  'Dekhte Dekhte',
];
